### ISSUE TITLE
Empty lines are removed

### ISSUE THREAD

**Issue by brauliobo** [slim-template/html2slim#22]
Hello, how can I keep empty lines from the original erb file so that the code don't appear all glued?

**Comment by joaomilho** [comment]
I don't see any empty line in this example. Am I missing something @brauliobo ?

**Comment by brauliobo** [comment]
@joaomilho html2haml/haml2slim does have the problem to remove empty lines too. The example I gave is just where the converted code looks better than with html2slim

**Comment by brauliobo** [comment]
@joaomilho try with the simplest example:

```html
<div>
  foo 
</div>

<div>
  bar 
</div>
```
