### ISSUE TITLE
erb2slim doesn't properly convert multiline embedded ruby segments

### ISSUE THREAD

**Issue by mjrk** [slim-template/html2slim#23]
Following code

    <%
    record = list_record if local_assigns[:list_record] # compat with render :partial :collection
    columns ||= list_columns
    row_id ||= element_row_id(:action => :list, :id => record.id)
    tr_class = cycle("", "even-record") + ' ' + list_row_class(record)
    action_links ||= active_scaffold_config.action_links.member
    data_refresh ||= record.to_param
    -%>

results in broken slim template code:

    | <% record = list_record if local_assigns[:list_record] columns ||= list_columns row_id ||= element_row_id(:action => :list, :id => record.id) tr_class = cycle("", "even-record") + ' ' + list_row_class(record) action_links ||= active_scaffold_config.action_links.member data_refresh ||= record.to_param -%>

**Comment by joaomilho** [comment]
Will look into it shortly.

**Comment by joaomilho** [comment]
Pushed version 0.0.8. Please let me know if it works for you.

**Comment by mjrk** [comment]
works like charm. Thanks!
